### ISSUE TITLE
Python 3 install issues due to print is a function, basestring vs str, and comma vs as

### ISSUE THREAD

**Issue by kbarnhart** [csdms/dakota#50]
In Python 3 print is a function, so easy_install resulted in a few print related errors there was also an issue of needing to change a comma to an "as".

To run the most basic examples, I had to replace basestring with str. 

These fixes are in a soon to be arriving PR.

**Comment by kbarnhart** [comment]
This issue superseded by issue #58 which concerns python 3 compatibility for all of dakotathon, not just install issues. 

It may be addressed by PR #59.

**Comment by mdpiper** [comment]
Another Python 3 install issue: we should use `setuptools>=24.3.0`; see http://www.python3statement.org/practicalities/. Of course, I just addressed this in 6ad1e069332fa6f3e6946aece71bf949433bcba9. Doh!

**Comment by mdpiper** [comment]
Fixed with #59.
