### ISSUE TITLE
Dynamic naming of directories and files

### ISSUE THREAD

**Issue by kbarnhart** [csdms/dakota#52]
Dakotathon presently does not support the dynamic naming of many directories and files. These include: 

- run directory
- work directory
- configuration file name
- parameter file name
-output file name 

Associated with this issue is hard coded placement of the configuration file, input file, and output file into the current directory (rather than a dynamically specified run directory which could default to the current directory).

This functionality would greatly improve dakotathon in two ways. By permitting a dynamic run_directory, a dakota object could be created and run by a looping script. By permitting a dynamic work_directory, the output can be placed in a different file structure (e.g. in a scratch directory).

**Comment by mdpiper** [comment]
Fixed with #57.
