### ISSUE TITLE
Removal of blocks

### ISSUE THREAD

**Issue by kbarnhart** [csdms/dakota#55]
In creating its output script, the dakota object always prints all of the standard blocks (e.g. 'method', 'variables', 'interface', 'responses'). It would be preferable to have a path to delete one or more of these blocks. 

For example, in order to *trick* dakota to running in parallel on beach, my analysis_driver script launches a qsub call and then creates temporary output so that dakota will move on. After the actual model run is finished, this temporary output is overwritten with real output which is then used for subsequent analysis. Thus, I don't want to include the environment block with creates a tabular data structure.

**Comment by mdpiper** [comment]
Fixed with #57.
