### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by kbarnhart** [csdms/dakota#58]
The dakotathon package is not presently compatible with python 3. This is reasonable given the original intentions of what python versions dakotathon would support. There are only a few changes to be made that would provide compatibility. 

See forthcoming PR.

This Issue supersedes #50 (which deals only with install issues).

**Comment by mdpiper** [comment]
Fixed with #59.

**Comment by kbarnhart** [comment]
thanks @mdpiper
