### ISSUE TITLE
python fork analysis driver

### ISSUE THREAD

**Issue by fab6** [csdms/dakota#79]
Hi

I am using dakota in combination with python for a while now with the following setup:
```
# INTERFACE
interface,
   fork
   evaluation_scheduling peer static
   analysis_drivers = 'run_opt.py'
   parameters_file = 'params.in'
   results_file = 'results.out'
   #asynchronous evaluation_concurrency = 24
   aprepro
```
The "run_opt.py" file is very similar to dakota's python example.

Now, I would like to use the fork interface with dakotathon. 
Though I am not sure if this is possible at all? It would be great, if you can give me a hint!

In addition, can somehow write, how actively is dakotathon further developed!?

Thanks in advance!
Fab

**Comment by mdpiper** [comment]
Hi Fab,

I haven't been able to work on dakotathon in awhile. I started it before the Dakota developers had a Python interface, but I'm pretty sure what they have now supersedes what I have in dakotathon. dakotathon is an open source project, though, so if you'd like to work on it, and improve it for your own use, you're welcome to it, and I would try to find the time to help you.

And in case you haven't seen it, an alternative to dakotathon is the [parsim](https://parsim.readthedocs.io/en/latest/) tool, which wraps all the Dakota methods and interfaces in Python.

mp

**Comment by fab6** [comment]
Hi,

thank you for your quick response. Ok, I undertand; I will check how I can handle it and would get back to you, when dakotathon is the right way to proceed.
Thank you very much!
